# Generated by Django 5.2.8 on 2025-11-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
