# Generated by Django 5.2.8 on 2025-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_rename_create_at_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], default='user', max_length=100),
        ),
    ]
